//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnit
    {
        public BusinessUnit()
        {
            this.AirFreights = new HashSet<AirFreight>();
            this.AirFreights1 = new HashSet<AirFreight>();
            this.BusinessUnitContacts = new HashSet<BusinessUnitContact>();
            this.CourierTransactions = new HashSet<CourierTransaction>();
            this.SeaFreights = new HashSet<SeaFreight>();
            this.SeaFreights1 = new HashSet<SeaFreight>();
            this.Shipments = new HashSet<Shipment>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int BusinessUnitTypeId { get; set; }
        public Nullable<int> ParentBusinessUnitId { get; set; }
        public bool isOperatingSite { get; set; }
        public bool hasAirPort { get; set; }
        public bool hasSeaPort { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual ICollection<AirFreight> AirFreights { get; set; }
        public virtual ICollection<AirFreight> AirFreights1 { get; set; }
        public virtual BusinessUnitType BusinessUnitType { get; set; }
        public virtual ICollection<BusinessUnitContact> BusinessUnitContacts { get; set; }
        public virtual ICollection<CourierTransaction> CourierTransactions { get; set; }
        public virtual ICollection<SeaFreight> SeaFreights { get; set; }
        public virtual ICollection<SeaFreight> SeaFreights1 { get; set; }
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
