//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public CheckIn()
        {
            this.CheckInShipments = new HashSet<CheckInShipment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CheckInTypeId { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<int> CheckInBusinessUnitId { get; set; }
        public Nullable<int> CheckInSourceId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual CheckInType CheckInType { get; set; }
        public virtual ICollection<CheckInShipment> CheckInShipments { get; set; }
    }
}
