//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInShipment
    {
        public int Id { get; set; }
        public int CheckInId { get; set; }
        public int ShipmentId { get; set; }
        public bool IsDisplay { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
