//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInType
    {
        public CheckInType()
        {
            this.CheckIns = new HashSet<CheckIn>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ReferenceTable { get; set; }
    
        public virtual ICollection<CheckIn> CheckIns { get; set; }
    }
}
