//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMunicipality
    {
        public CityMunicipality()
        {
            this.Addresses = new HashSet<Address>();
            this.ServiceableAreas = new HashSet<ServiceableArea>();
            this.CustomerAddresses = new HashSet<CustomerAddress>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int StateProvinceId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual ICollection<ServiceableArea> ServiceableAreas { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
    }
}
