//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.BusinessUnitContacts = new HashSet<BusinessUnitContact>();
            this.ContactPhones = new HashSet<ContactPhone>();
            this.CustomerContacts = new HashSet<CustomerContact>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string AlternateEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual ICollection<BusinessUnitContact> BusinessUnitContacts { get; set; }
        public virtual ICollection<ContactPhone> ContactPhones { get; set; }
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
    }
}
