//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierTransaction
    {
        public CourierTransaction()
        {
            this.CourierTransactionDetails = new HashSet<CourierTransactionDetail>();
        }
    
        public int Id { get; set; }
        public int CourierId { get; set; }
        public int BusinessUnitId { get; set; }
        public decimal CourierCost { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<System.TimeSpan> CallTime { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.TimeSpan> CompletedTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Courier Courier { get; set; }
        public virtual ICollection<CourierTransactionDetail> CourierTransactionDetails { get; set; }
    }
}
