//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryException
    {
        public int Id { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<System.DateTime> DexDate { get; set; }
        public Nullable<System.TimeSpan> DexTime { get; set; }
        public int DexType { get; set; }
        public string DexRemarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual DeliveryExceptionType DeliveryExceptionType { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
