//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryExceptionType
    {
        public DeliveryExceptionType()
        {
            this.DeliveryExceptions = new HashSet<DeliveryException>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<DeliveryException> DeliveryExceptions { get; set; }
    }
}
