//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuAccess
    {
        public MenuAccess()
        {
            this.UserMenus = new HashSet<UserMenu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string Access { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<UserMenu> UserMenus { get; set; }
    }
}
