//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuAccesses = new HashSet<MenuAccess>();
            this.UserMenus = new HashSet<UserMenu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public string IconClass { get; set; }
        public string IsParent { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<MenuAccess> MenuAccesses { get; set; }
        public virtual ICollection<UserMenu> UserMenus { get; set; }
    }
}
