//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KunzadDbEntities : DbContext
    {
        public KunzadDbEntities()
            : base("name=KunzadDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirFreight> AirFreights { get; set; }
        public virtual DbSet<AirFreightShipment> AirFreightShipments { get; set; }
        public virtual DbSet<AirLine> AirLines { get; set; }
        public virtual DbSet<BusinessUnit> BusinessUnits { get; set; }
        public virtual DbSet<BusinessUnitContact> BusinessUnitContacts { get; set; }
        public virtual DbSet<BusinessUnitType> BusinessUnitTypes { get; set; }
        public virtual DbSet<Charge> Charges { get; set; }
        public virtual DbSet<CityMunicipality> CityMunicipalities { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactNumberType> ContactNumberTypes { get; set; }
        public virtual DbSet<ContactPhone> ContactPhones { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Courier> Couriers { get; set; }
        public virtual DbSet<CourierTransaction> CourierTransactions { get; set; }
        public virtual DbSet<CourierTransactionDetail> CourierTransactionDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<SeaFreight> SeaFreights { get; set; }
        public virtual DbSet<SeaFreightShipment> SeaFreightShipments { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceableArea> ServiceableAreas { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }
        public virtual DbSet<ServiceCharge> ServiceCharges { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<ShipmentCharge> ShipmentCharges { get; set; }
        public virtual DbSet<ShipmentDimension> ShipmentDimensions { get; set; }
        public virtual DbSet<ShipmentType> ShipmentTypes { get; set; }
        public virtual DbSet<ShippingLine> ShippingLines { get; set; }
        public virtual DbSet<StateProvince> StateProvinces { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<Trucker> Truckers { get; set; }
        public virtual DbSet<Trucking> Truckings { get; set; }
        public virtual DbSet<TruckingDelivery> TruckingDeliveries { get; set; }
        public virtual DbSet<TruckType> TruckTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vessel> Vessels { get; set; }
        public virtual DbSet<VesselVoyage> VesselVoyages { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
    }
}
