//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatesDetail
    {
        public int Id { get; set; }
        public Nullable<int> RateMasterId { get; set; }
        public Nullable<int> ChargeId { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public string Computation { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> ExcessOf { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
    
        public virtual RatesMaster RatesMaster { get; set; }
    }
}
