//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaFreight
    {
        public SeaFreight()
        {
            this.SeaFreightShipments = new HashSet<SeaFreightShipment>();
        }
    
        public int Id { get; set; }
        public string BLNumber { get; set; }
        public System.DateTime BLDate { get; set; }
        public int VesselVoyageId { get; set; }
        public int OriginBusinessUnitId { get; set; }
        public int DestinationBusinessUnitId { get; set; }
        public decimal FreightCost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual BusinessUnit BusinessUnit1 { get; set; }
        public virtual VesselVoyage VesselVoyage { get; set; }
        public virtual ICollection<SeaFreightShipment> SeaFreightShipments { get; set; }
    }
}
