//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.RatesMasters = new HashSet<RatesMaster>();
            this.ServiceCharges = new HashSet<ServiceCharge>();
            this.Shipments = new HashSet<Shipment>();
            this.ShipmentTypes = new HashSet<ShipmentType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ServiceCategoryId { get; set; }
        public string Description { get; set; }
        public bool IsMultimodal { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal MaxWeight { get; set; }
        public Nullable<int> DeliveryWorkingDays { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual ICollection<RatesMaster> RatesMasters { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<ServiceCharge> ServiceCharges { get; set; }
        public virtual ICollection<Shipment> Shipments { get; set; }
        public virtual ICollection<ShipmentType> ShipmentTypes { get; set; }
    }
}
