//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCharge
    {
        public ServiceCharge()
        {
            this.ShipmentCharges = new HashSet<ShipmentCharge>();
        }
    
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int ChargeId { get; set; }
        public string ChargeName { get; set; }
        public bool IsTaxInclusive { get; set; }
        public decimal TaxPercentage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual Charge Charge { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<ShipmentCharge> ShipmentCharges { get; set; }
    }
}
