//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentCharge
    {
        public int Id { get; set; }
        public int ShipmentId { get; set; }
        public int ServiceChargeId { get; set; }
        public string ServiceChargeName { get; set; }
        public decimal Amount { get; set; }
        public bool IsTaxInclusive { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TaxPercentage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual ServiceCharge ServiceCharge { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
