//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.AirFreightShipments = new HashSet<AirFreightShipment>();
            this.CourierTransactionDetails = new HashSet<CourierTransactionDetail>();
            this.SeaFreightShipments = new HashSet<SeaFreightShipment>();
            this.ShipmentCharges = new HashSet<ShipmentCharge>();
            this.ShipmentDimensions = new HashSet<ShipmentDimension>();
            this.TruckingDeliveries = new HashSet<TruckingDelivery>();
        }
    
        public int Id { get; set; }
        public int BusinessUnitId { get; set; }
        public int ServiceId { get; set; }
        public int ShipmentTypeId { get; set; }
        public string PaymentMode { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> BillToCustomerId { get; set; }
        public short Quantity { get; set; }
        public decimal TotalCBM { get; set; }
        public bool IsRevenue { get; set; }
        public decimal Revenue { get; set; }
        public bool IsTaxInclusive { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TaxPercentage { get; set; }
        public string Description { get; set; }
        public string DeliverTo { get; set; }
        public int DeliveryAddressId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public string ReceivedByName { get; set; }
        public int ParentShipmentId { get; set; }
        public bool IsConsolidation { get; set; }
        public bool IsMultipleDelivery { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<System.TimeSpan> PickUpTime { get; set; }
        public string DeliverToContactNumber { get; set; }
        public string Origin { get; set; }
    
        public virtual ICollection<AirFreightShipment> AirFreightShipments { get; set; }
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ICollection<CourierTransactionDetail> CourierTransactionDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SeaFreightShipment> SeaFreightShipments { get; set; }
        public virtual Service Service { get; set; }
        public virtual ShipmentType ShipmentType { get; set; }
        public virtual ICollection<ShipmentCharge> ShipmentCharges { get; set; }
        public virtual ICollection<ShipmentDimension> ShipmentDimensions { get; set; }
        public virtual ICollection<TruckingDelivery> TruckingDeliveries { get; set; }
    }
}
