//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunzad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckType
    {
        public TruckType()
        {
            this.Trucks = new HashSet<Truck>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> WeightCapacity { get; set; }
        public Nullable<decimal> VolumeCapacity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastUpdatedByUserId { get; set; }
    
        public virtual ICollection<Truck> Trucks { get; set; }
    }
}
